version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./backend:/app
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
      - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY} 